language: node_js
node_js: "10.9"
cache:
  directories:
    - node_modules

env:
  global:
    - GITHUB_REF: github.com/mengqi92/mengqi92.github.io.git

addons:
  apt:
    packages:
      - graphviz

before_install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - wget https://github.com/jgm/pandoc/releases/download/2.8.0.1/pandoc-2.8.0.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.8.0.1-1-amd64.deb
install:
  - npm install
script:
  - hexo cl
  - hexo g --debug -b
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: master
  local_dir: ./public/
  on:
    branch: blog-reloaded
branches:
  only:
    - blog-reloaded
